// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgBbI1h066g3LC2_yEtKYXi3BnoUBzb9E',
    appId: '1:86996345197:web:b11984ccf112d1ea4b3a64',
    messagingSenderId: '86996345197',
    projectId: 'flutter-lab-2715c',
    authDomain: 'flutter-lab-2715c.firebaseapp.com',
    storageBucket: 'flutter-lab-2715c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBII66nzW2VWOT1cjwPWa2ApCsvf-Fyfq8',
    appId: '1:86996345197:android:6a3aa9906ed68f4b4b3a64',
    messagingSenderId: '86996345197',
    projectId: 'flutter-lab-2715c',
    storageBucket: 'flutter-lab-2715c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNfnD_3kVvIvueZVG55QQ8I_QkJAjOPic',
    appId: '1:86996345197:ios:5c775955899ae1e44b3a64',
    messagingSenderId: '86996345197',
    projectId: 'flutter-lab-2715c',
    storageBucket: 'flutter-lab-2715c.appspot.com',
    iosClientId: '86996345197-c2ddg6647h6hp08mflli08ie2mca7lf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNfnD_3kVvIvueZVG55QQ8I_QkJAjOPic',
    appId: '1:86996345197:ios:5c775955899ae1e44b3a64',
    messagingSenderId: '86996345197',
    projectId: 'flutter-lab-2715c',
    storageBucket: 'flutter-lab-2715c.appspot.com',
    iosClientId: '86996345197-c2ddg6647h6hp08mflli08ie2mca7lf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
